// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxSim.Backend.Data;

#nullable disable

namespace TaxSim.Backend.Migrations
{
    [DbContext(typeof(TaxSimDbContext))]
    partial class TaxSimDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("TaxSim.Backend.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskFlag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SimulationRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaxAgentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SimulationRunId");

                    b.HasIndex("TaxAgentId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TaxSim.Backend.Models.SimulationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComplianceFailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RunTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaxPolicyId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalRevenueCollected")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaxPolicyId");

                    b.ToTable("SimulationRuns");
                });

            modelBuilder.Entity("TaxSim.Backend.Models.TaxAgent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BehavioralProfile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Income")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaxAgents");
                });

            modelBuilder.Entity("TaxSim.Backend.Models.TaxPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NaturalLanguageRule")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaxPolicies");
                });

            modelBuilder.Entity("TaxSim.Backend.Models.AuditLog", b =>
                {
                    b.HasOne("TaxSim.Backend.Models.SimulationRun", "SimulationRun")
                        .WithMany("AuditLogs")
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxSim.Backend.Models.TaxAgent", "TaxAgent")
                        .WithMany("AuditLogs")
                        .HasForeignKey("TaxAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationRun");

                    b.Navigation("TaxAgent");
                });

            modelBuilder.Entity("TaxSim.Backend.Models.SimulationRun", b =>
                {
                    b.HasOne("TaxSim.Backend.Models.TaxPolicy", "TaxPolicy")
                        .WithMany("SimulationRuns")
                        .HasForeignKey("TaxPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxPolicy");
                });

            modelBuilder.Entity("TaxSim.Backend.Models.SimulationRun", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("TaxSim.Backend.Models.TaxAgent", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("TaxSim.Backend.Models.TaxPolicy", b =>
                {
                    b.Navigation("SimulationRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
